### ISSUE TITLE
Editor doesn't save keymode allowing notes to be out of the playfield

### ISSUE THREAD

**Issue by Comprobar** [TeamFluXis/fluXis#23]
https://github.com/TeamFluXis/fluXis/assets/91441010/b254d4ed-e088-492f-8ef7-836e606c1551

Also noticed that i cannot save the map after changing the keymode.

https://github.com/TeamFluXis/fluXis/assets/91441010/d990ff04-bd5a-4f47-a2ef-da94e56df477

**Comment by flustix** [comment]
Fixed with [1018762](https://github.com/TeamFluXis/fluXis/commit/1018762fab29017e88cd492dc02be66cdaff89cf)
