### ISSUE TITLE
Notes are invisible at the beginning of maps

### ISSUE THREAD

**Issue by Comprobar** [TeamFluXis/fluXis#8]
The title and the video are selfexplanatory. 

https://github.com/TeamFluXis/fluXis/assets/91441010/c66c532b-1763-4664-bb46-0f02084cb028

Logs:
[input.log](https://github.com/TeamFluXis/fluXis/files/12709179/input.log)
[network.log](https://github.com/TeamFluXis/fluXis/files/12709174/network.log)
[performance.log](https://github.com/TeamFluXis/fluXis/files/12709175/performance.log)
[runtime.log](https://github.com/TeamFluXis/fluXis/files/12709176/runtime.log)
[update.log](https://github.com/TeamFluXis/fluXis/files/12709177/update.log)

**Comment by flustix** [comment]
Seems to be an issue related to negative audio offset.
Still searching for a fix.

**Comment by flustix** [comment]
Seems to be fixed with [015d794](https://github.com/TeamFluXis/fluXis/commit/015d7940f79ad77dc2e9feb6ba569b7cd7238039).
